deployment:
  tasks:
    - export DEPLOY_PATH=/home/shehngzw/public_html
    - echo "Deploying to ${DEPLOY_PATH}"
    
    - export REPOSITORY_NAME=Portfolio
    - echo "Cloning repository ${REPOSITORY_NAME}"
    
    # Check if directory exists, clone or pull from repo
    - '[ ! -d "${DEPLOY_PATH}/${REPOSITORY_NAME}" ] && /bin/git clone https://github.com/Nevanxx/${REPOSITORY_NAME}.git ${DEPLOY_PATH} || (cd ${DEPLOY_PATH}/${REPOSITORY_NAME} && /bin/git pull)'
    
    - echo "Setting file permissions"
    - /bin/chmod -R 755 ${DEPLOY_PATH}
    
    - echo "Deployment complete!"
